---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-pod-reaper
  namespace: job-pod-reaper
spec:
  selector:
    matchLabels:
      app: job-pod-reaper
  template:
    metadata:
      labels:
        app: job-pod-reaper
    spec:
      serviceAccountName: job-pod-reaper
      containers:
      - name: job-pod-reaper
        image: docker.io/ohiosupercomputer/job-pod-reaper:latest
        imagePullPolicy: Always
        args:
        - --reap-max=30
        - --reap-interval=60s
        - --reap-namespaces=all
        - --job-label=job
        - --listen-address=:8080
        - --log-level=info
        - --log-format=logfmt
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 50Mi
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: job-pod-reaper
  namespace: job-pod-reaper
  labels:
    app.kubernetes.io/name: job-pod-reaper
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: job-pod-reaper
