name: Release Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    name: Release Docker
    steps:
      - name: Set version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push latest
        if: ${{ github.ref == 'refs/heads/main' }}
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ohiosupercomputer/job-pod-reaper:latest
      - name: Build and push tag ${{ steps.tag.outputs.tag }}
        if: ${{ github.ref != 'refs/heads/main' }}
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ohiosupercomputer/job-pod-reaper:${{ steps.tag.outputs.tag }}
      - name: Image digest
        if: steps.docker_build_latest.outputs.digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
      - name: Image digest
        if: steps.docker_build_tag.outputs.digest
        run: echo ${{ steps.docker_build_tag.outputs.digest }}
