name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout=2m
      - name: Run tests
        run: make all
      - name: Run coverage
        run: make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: make build
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --rm-dist --snapshot
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: docker.io/ohiosupercomputer/job-pod-reaper:latest
          outputs: type=docker,dest=/tmp/job-pod-reaper.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp/job-pod-reaper.tar
  test-helm:
    needs: [build]
    runs-on: ubuntu-latest
    name: Test Helm Chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Run chart-testing (lint)
        run: ct lint --target-branch=main --check-version-increment=false
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.18.0
          cluster_name: kind
      - name: Load image
        run: |
          docker load --input /tmp/job-pod-reaper.tar
          kind load docker-image docker.io/ohiosupercomputer/job-pod-reaper:latest
      - name: Update chart values
        run: |
          sed -i \
            -e 's|tag:.*|tag: latest|g' \
            charts/job-pod-reaper/values.yaml
          cat charts/job-pod-reaper/values.yaml
      - name: Run chart-testing (install)
        run: ct install --target-branch=main
